services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./backend/app:/usr/src/app/app
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      # Montar archivos específicos
      - ./frontend/index.html:/app/index.html
      - ./frontend/main.ts:/app/main.ts
      - ./frontend/dashboard.ts:/app/dashboard.ts
      - ./frontend/dashboard.html:/app/dashboard.html
      - ./frontend/styles.css:/app/styles.css
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/redirect.html:/app/redirect.html
      - ./frontend/env-config.js:/app/env-config.js
      - ./frontend/env-types.js:/app/env-types.js
      - ./.env:/app/.env
      - ./frontend/pong.html:/app/pong.html
      - ./frontend/pong:/app/pong
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm install -g http-server nodemon &&
             nodemon --watch /app/dashboard --watch /app/pong --watch /app/pong.html --ext js,ts,html,css,json,png,jpg,hdr,gltf --exec 'http-server . -p 8080 --cors -c-1'"
    depends_on:
      - backend
